# Generated by Django 4.1.6 on 2023-03-01 21:36

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listingimage_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='images',
            field=models.ImageField(upload_to='Images/Listings/', validators=[auctions.models.validate_image_extension]),
        ),
    ]
