# Generated by Django 4.1.6 on 2023-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listingimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home & Garden', 'Home & Garden'), ('Sports & Outdoors', 'Sports & Outdoors')], default="Other", max_length=20),
            preserve_default=False,
        ),
    ]
