# Generated by Django 4.1.6 on 2023-03-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date']},
        ),
    ]
