# Generated by Django 4.1.6 on 2023-03-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_date_added_user_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='startingBid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBids', to='auctions.listing'),
        ),
    ]
