# Generated by Django 4.1.6 on 2023-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Collectibles & Art', 'Collectibles & Art'), ('Sporting Goods', 'Sporting Goods'), ('Health & Beauty', 'Health & Beauty'), ('Motors', 'Motors'), ('Business & Industrial', 'Business & Industrial'), ('Other', 'Other')], max_length=50),
        ),
    ]
